@echo off
rem Auto-generated by scripts/setup_env.py - do not edit
set "QMT_ROOT=D:\gjqmt"
set "MINQMT_WORKSPACE=E:\cursor_workspace"
set "MINQMT_PYTHON_EXE=C:\Users\Rhett\AppData\Local\Programs\Python\Python39\python.exe"
set "MINQMT_PYTHON=Python 3.9 (C:\Users\Rhett\AppData\Local\Programs\Python\Python39\python.exe)"
set "PYTHONPATH=E:\cursor_workspace"
set "PATH=D:\gjqmt\bin.x64;D:\gjqmt\bin.x64\Lib\site-packages\xtquant;%PATH%"
